In [ ]:
%matplotlib inline


Введение в PyTorch
================

Это основанный на Python научный вычислительный пакет, ориентированный на два набора аудиторий:

* замена NumPy для использования мощности графических процессоров
* исследовательская платформа глубокого обучения которая обеспечивает максимальную гибкость и скорость

Начало
---------------

Тензоры

^^^^^^^

Тензоры похожи на ndarrays библиотеки numpy, с добавлением того, что
Тензоры также могут быть использованы на графическом процессоре для ускорения вычислений.



In [1]:
from __future__ import print_function
import torch
print(torch.cuda.is_available())

True


#### Примечание
Неинициализированная тензор объявляется, но не содержит определенных известных значений до ее использования. Когда создается неинициализированная матрица, все значения, которые были в выделенной памяти в то время, будут отображаться как начальные значения.



Создадим неинициализированный тензор 5x3:



In [2]:
x = torch.empty(5, 3)
print(x)
type(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


torch.Tensor

Создадим тензор со случайным набором:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1494, 0.5984, 0.3142],
        [0.8836, 0.0737, 0.7727],
        [0.0510, 0.4903, 0.8239],
        [0.3205, 0.4145, 0.3501],
        [0.3415, 0.7868, 0.1584]])


Создадим тензор заполненный 0 типа long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Создадим тензор из списка и изменим его тип:





In [5]:
x = torch.tensor([5.5, 3])
print(x)
x.type(torch.int)

tensor([5.5000, 3.0000])


tensor([5, 3], dtype=torch.int32)


или создадим тензор на основе существующего тензора. Эти методы будут повторно использовать свойства входного тензора, например тип, если только пользователь не предоставит новые значения

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* метод применяется для размера
print(x)

x = torch.randn_like(x, dtype=torch.float64)    #  dtype позволяет сменить тип!
print(x)                                      

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8267, -1.1563, -1.2982],
        [ 0.6280,  0.6734, -1.5078],
        [ 0.5554, -0.1539, -0.5424],
        [ 1.2964, -0.9539,  1.2995],
        [-0.2428, -1.6030,  1.9262]], dtype=torch.float64)


Получим размер тензора:



In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
x1 = torch.tensor([[1, 2], [3, 4]])
y=torch.unsqueeze(x1,0)
print(y,y.size())
z=torch.unsqueeze(x1,-1)
print(z,z.size())
t=torch.unsqueeze(x1,1)
print(t,t.size())

tensor([[[1, 2],
         [3, 4]]]) torch.Size([1, 2, 2])
tensor([[[1],
         [2]],

        [[3],
         [4]]]) torch.Size([2, 2, 1])
tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2])


#### Примечание
`torch.Size` это кортеж и поддерживает все операции для кортежей

Операции

^^^^^^^^^^

Существует несколько синтаксисов для операций. В следующем
примере мы рассмотрим операцию сложения.

Сложение: синтаксис 1-й



In [9]:
y = torch.rand(5, 3)
print(x,'\n',y)
print(x + y)

tensor([[-0.8267, -1.1563, -1.2982],
        [ 0.6280,  0.6734, -1.5078],
        [ 0.5554, -0.1539, -0.5424],
        [ 1.2964, -0.9539,  1.2995],
        [-0.2428, -1.6030,  1.9262]], dtype=torch.float64) 
 tensor([[0.3440, 0.4754, 0.7106],
        [0.7390, 0.9189, 0.3084],
        [0.7960, 0.3156, 0.8808],
        [0.8521, 0.5606, 0.9925],
        [0.3763, 0.7499, 0.4190]])
tensor([[-0.4827, -0.6808, -0.5876],
        [ 1.3669,  1.5923, -1.1994],
        [ 1.3514,  0.1617,  0.3385],
        [ 2.1485, -0.3933,  2.2920],
        [ 0.1335, -0.8531,  2.3452]], dtype=torch.float64)


Сложение: синтаксис 2-й



In [10]:
print(torch.add(x, y))

tensor([[-0.4827, -0.6808, -0.5876],
        [ 1.3669,  1.5923, -1.1994],
        [ 1.3514,  0.1617,  0.3385],
        [ 2.1485, -0.3933,  2.2920],
        [ 0.1335, -0.8531,  2.3452]], dtype=torch.float64)


Сложение: с выходным тензором в качестве аргумента



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.4827, -0.6808, -0.5876],
        [ 1.3669,  1.5923, -1.1994],
        [ 1.3514,  0.1617,  0.3385],
        [ 2.1485, -0.3933,  2.2920],
        [ 0.1335, -0.8531,  2.3452]])


Сложение: в одно действие (in-place)

In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.4827, -0.6808, -0.5876],
        [ 1.3669,  1.5923, -1.1994],
        [ 1.3514,  0.1617,  0.3385],
        [ 2.1485, -0.3933,  2.2920],
        [ 0.1335, -0.8531,  2.3452]])


#### Примечание

Любая операция, которая изменяет тензор в одно действие сопровождается ``_``. Например: ``x.copy_(y)``, ``x.t_()``, изменят ``x``.

Вы можете так же использовать стандартную NumPy-подобную индексацию со всеми ее особенностями!

In [13]:
print(x[:, 1])

tensor([-1.1563,  0.6734, -0.1539, -0.9539, -1.6030], dtype=torch.float64)


Изменение размера: Если вы хотите изменить размер/форму тензора, вы можете использовать ``torch.view``:

In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # размер -1 соответсвует остальным размерностям, т.е. 16/8=2 
print(x.size(), y.size(), z.size())
x,y

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


(tensor([[-1.2489,  1.1025,  1.2018,  0.9876],
         [-0.4437,  1.1579, -0.7168,  0.9765],
         [-0.6405, -0.0598,  0.7829,  0.0752],
         [-0.5814,  1.1910,  0.3383, -0.1666]]),
 tensor([-1.2489,  1.1025,  1.2018,  0.9876, -0.4437,  1.1579, -0.7168,  0.9765,
         -0.6405, -0.0598,  0.7829,  0.0752, -0.5814,  1.1910,  0.3383, -0.1666]))

Если у вас есть одноэлементный тензор, используйте `.item ()`, чтобы получить его значение

In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2251])
0.22505801916122437


**Далее:**

100+ тензорные операции, в том числе транспонирование, индексирование, нарезка, математические операции, линейная алгебра, случайные числа и др описаны здесь: <https://pytorch.org/docs/torch>

Переход с NumPy
------------
Преобразование Torch Tensor в массив NumPy и наоборот-это легко.

Torch Tensor и массив NumPy будут совместно использовать свои базовые
ячейки памяти (если Torch Tensor находится на процессоре), и изменение одного изменит другое.

Преобразование Torch Tensor в массив NumPy

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


Посмотрим как массив NumPy изменяется в своих значениях.

In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Преобразование массива NumPy в Torch тензор

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Посмотрим как изменения nparray отразятся на тензоре 


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



Все тензоры на CPU за исключением CharTensor поддерживают преобразование в NumPy и обратно.

CUDA тензоры
------------

Тензоры могут быть перемещены на любой процессор методом ``.to``



In [25]:
# Данный код выполняется только, если доступен CUDA
# Для смены реализации тензора на и с GPU используется объект ``torch.device``
if torch.cuda.is_available():
    device = torch.device("cuda")          # это объект device типа CUDA  
    y = torch.ones_like(x, device=device)  # создает тензор на GPU
    x = x.to(device)                       # можно использовать ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # метод ``.to`` может также менять dtype!

tensor([1.2251], device='cuda:0')
tensor([1.2251], dtype=torch.float64)


Соединение тензоров
--------

Метод `torch.cat` соединяет тензоры вдоль заданного направления. Другой способ использовать `torch.stack`.

In [ ]:
x=torch.ones(5)
y=x.add(1)
z=x.add(2)
t1 = torch.cat([x, y, z])
print(t1)

tensor([1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3.])


In [ ]:
t2=torch.vstack([x,y,z])
print(t2)

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.]])


In [26]:
t3=torch.hstack([x.view(-1,1),y.view(-1,1),z.view(-1,1)])
print(t3)

tensor([[0.2251, 1.0000, 1.2251]], device='cuda:0')


Преобразование одноэлементных тензоров.
----
Рссмотрим одноэлементный тензор, полученный, например агрегацией всех элементов тензора в одно значение, его можно сразу же перевести в численное значение Python методом `item()`:

In [27]:
agg = x.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

0.22505801916122437 <class 'float'>


Операции на месте
----
Операции, которые сохраняют значение вычисления в переменной которая участвовала в вычислениях называются операциями на месте. Они обозначаются суффиксом `_`. Например: `x.copy_(y)`, `x.t_()`, изменят `x`. 

Примечание: Операции на месте сохраняют немного памяти, но могут вызвать проблемы при вычислении производных потому, что мгновенно теряют предыдущее значение, поэтому использование их не поощеряется.


In [28]:
print(x, "\n")
x.add_(5)
print(x)

tensor([0.2251], device='cuda:0') 

tensor([5.2251], device='cuda:0')


Матричные операции
---


## Задание 1.
Создать тензор размера 5 на 5, содержащий случайный набор числел в ячейках на диагонали и выше, ниже диагонали содержащий 0.


In [32]:
import torch

tensor = torch.triu(torch.rand((5, 5)))
print(tensor)

tensor([[0.8355, 0.0699, 0.2696, 0.3175, 0.7489],
        [0.0000, 0.8252, 0.6542, 0.9899, 0.8327],
        [0.0000, 0.0000, 0.0302, 0.0814, 0.2342],
        [0.0000, 0.0000, 0.0000, 0.5901, 0.0161],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.7291]])


## Задание 2.
Найти тезор обратный этому тензору.Задание 2.
Найти тезор обратный этому тензору.

In [33]:
inversed = torch.inverse(tensor)
print(inversed)

tensor([[ 1.1969e+00, -1.0141e-01, -8.4957e+00,  6.9803e-01,  1.6003e+00],
        [-0.0000e+00,  1.2119e+00, -2.6276e+01,  1.5917e+00,  7.0221e+00],
        [ 0.0000e+00, -0.0000e+00,  3.3144e+01, -4.5717e+00, -1.0546e+01],
        [ 0.0000e+00, -2.0730e-08, -5.4103e-06,  1.6945e+00, -3.7472e-02],
        [ 0.0000e+00, -5.3748e-09, -6.9357e-07,  1.1094e-07,  1.3715e+00]])


Задание 3.
---
Сгенерируйте тензор случайных значений формы (10,10) с нормальным распределением значений со средним 2, и стандартным отклонением 3. Постройте матрицу парных расстояний между строками этой матрицы, найдите средние и стандартное отклонение нового тензора.

In [39]:
tensor = torch.randn(10, 10) * 3 + 2
print("Mean: ", torch.mean(tensor))
print("Standard Deviation: ", torch.std(tensor))

Mean:  tensor(1.5731)
Standard Deviation:  tensor(2.7981)


In [40]:
dev = torch.cdist(tensor, tensor)
print("Mean: ", torch.mean(dev))
print("Standard Deviation: ", torch.std(dev))

Mean:  tensor(11.0053)
Standard Deviation:  tensor(4.2861)


Задание 4
---
Создайте тензор A, используя значения range(9). Разбить тензор на 3 одинаковых тензора a,b,c разбить тензор A на два тензора d, e, содержащие 5 и 4 значения из A, соединить тензоры d и e в обратном порядке. Составить из тензоров a, b, c тензор формы (3,3).

In [41]:
A_values = range(9)
A = torch.tensor(A_values)
print("Start data: ", A)

a, b, c = torch.split(A, 3)
print("a: ",a)
print("b: ",b)
print("c: ",c)

d, e = torch.split(A, [5, 4])
print("d: ",d)
print("e: ",e)

de = torch.cat((e, d), dim=0)
print("de: ",de)

Start data:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
a:  tensor([0, 1, 2])
b:  tensor([3, 4, 5])
c:  tensor([6, 7, 8])
d:  tensor([0, 1, 2, 3, 4])
e:  tensor([5, 6, 7, 8])
de:  tensor([5, 6, 7, 8, 0, 1, 2, 3, 4])


Задание 5
---
Проверить скорость выполнения матричного умножения на CPU и GPU. 

In [42]:
import time

a = torch.randn(10000, 10000)
b = torch.randn(10000, 10000)

start_time = time.time()
c = torch.matmul(a, b)
end_time = time.time()
execution_time_cpu = end_time - start_time

print("Execution time for CPU:", execution_time_cpu)

a_gpu = a.cuda()
b_gpu = b.cuda()
start_time = time.time()
c_gpu = torch.matmul(a_gpu, b_gpu)
end_time = time.time()
execution_time_gpu = end_time - start_time

print("Execution time for GPU:", execution_time_gpu)

Execution time for CPU: 26.814736127853394
Execution time for GPU: 3.109980344772339
